"""
# DETERMINISM RULES (for exact reproducibility):
# 1. Coordinates are 0-indexed (row, col) with (0,0) at the top-left of the grid.
# 2. Neighbors are generated in the strict order: Up (-1,0), Down (+1,0), Left (0,-1), Right (0,+1).
# 3. Min-heap frontier entries are tuples of: (f_score, h_score, tie_breaker_counter, node).
# 4. "States expanded" counts nodes popped from the frontier and added to the closed set.
#    Stale (duplicate) frontier pops of already-closed nodes are skipped and NOT counted.

[LLM-GENERATED CODE] - Generated by Gemini AI based on student specification.
"""

import heapq
import math


def manhattan_distance(p1, p2):
    """Calculates the Manhattan distance between two grid points (r1, c1) and (r2, c2)."""
    return abs(p1[0] - p2[0]) + abs(p1[1] - p2[1])


def euclidean_distance(p1, p2):
    """Calculates the Euclidean distance between two grid points (r1, c1) and (r2, c2)."""
    return math.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)


def zero_distance(p1, p2):
    """Uninformed heuristic h(n) = 0 for Dijkstra equivalence."""
    return 0


def get_neighbors(grid, pos):
    """
    Generates valid adjacent passable cells ('.', 'S', 'G') from current pos (row, col).
    Enforces deterministic order: Up, Down, Left, Right.
    """
    r, c = pos
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # Up, Down, Left, Right
    neighbors = []
    num_rows = len(grid)
    num_cols = len(grid[0])

    for dr, dc in directions:
        nr, nc = r + dr, c + dc
        if 0 <= nr < num_rows and 0 <= nc < num_cols:
            if grid[nr][nc] != '#':
                neighbors.append((nr, nc))
    return neighbors


def astar_search(grid, start, goal, heuristic_func=manhattan_distance):
    """
    Executes A* search on a 2D grid from start to goal using the given heuristic function.
    
    Returns:
        found (bool): True if goal reached, False otherwise.
        path (list): List of (row, col) tuples from start to goal, or [] if no path.
        path_length (int): Total number of moves (len(path) - 1), or 0 if no path.
        states_expanded (int): Total number of unique nodes popped and added to closed set.
    """
    tie_breaker = 0
    h_start = heuristic_func(start, goal)
    f_start = 0 + h_start

    # Min-heap frontier containing (f, h, counter, node)
    frontier = [(f_start, h_start, tie_breaker, start)]
    
    g_score = {start: 0}
    parent = {start: None}
    closed_set = set()
    states_expanded = 0

    while frontier:
        f, h, counter, current = heapq.heappop(frontier)

        # Skip stale pops (nodes already expanded)
        if current in closed_set:
            continue

        closed_set.add(current)
        states_expanded += 1

        # Goal test upon expanding node
        if current == goal:
            path = []
            curr = goal
            while curr is not None:
                path.append(curr)
                curr = parent[curr]
            path.reverse()
            return True, path, len(path) - 1, states_expanded

        for neighbor in get_neighbors(grid, current):
            tentative_g = g_score[current] + 1

            if neighbor not in g_score or tentative_g < g_score[neighbor]:
                g_score[neighbor] = tentative_g
                parent[neighbor] = current
                h_neighbor = heuristic_func(neighbor, goal)
                f_neighbor = tentative_g + h_neighbor
                tie_breaker += 1
                heapq.heappush(frontier, (f_neighbor, h_neighbor, tie_breaker, neighbor))

    return False, [], 0, states_expanded
