"""
# DETERMINISM RULES (for exact reproducibility):
# 1. Coordinates are 0-indexed (row, col) with (0,0) at the top-left of the grid.
# 2. Neighbors are generated in the strict order: Up (-1,0), Down (+1,0), Left (0,-1), Right (0,+1).
# 3. Queue operates strictly FIFO (First-In, First-Out) via collections.deque.
# 4. "States expanded" counts nodes popped from the queue and processed.
#    Nodes visited are marked upon push/pop to avoid reprocessing.

[LLM-GENERATED CODE] - Generated by Gemini AI based on student specification.
"""

from collections import deque


def get_neighbors(grid, pos):
    """
    Generates valid adjacent passable cells ('.', 'S', 'G') from current pos (row, col).
    Enforces deterministic order: Up, Down, Left, Right.
    """
    r, c = pos
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # Up, Down, Left, Right
    neighbors = []
    num_rows = len(grid)
    num_cols = len(grid[0])

    for dr, dc in directions:
        nr, nc = r + dr, c + dc
        if 0 <= nr < num_rows and 0 <= nc < num_cols:
            if grid[nr][nc] != '#':
                neighbors.append((nr, nc))
    return neighbors


def bfs_search(grid, start, goal):
    """
    Executes Breadth-First Search (BFS) on a 2D grid from start to goal.
    
    Returns:
        found (bool): True if goal reached, False otherwise.
        path (list): List of (row, col) tuples from start to goal, or [] if no path.
        path_length (int): Total number of moves (len(path) - 1), or 0 if no path.
        states_expanded (int): Total number of unique nodes dequeued and processed.
    """
    queue = deque([start])
    visited = set([start])
    parent = {start: None}
    states_expanded = 0

    while queue:
        current = queue.popleft()
        states_expanded += 1

        if current == goal:
            path = []
            curr = goal
            while curr is not None:
                path.append(curr)
                curr = parent[curr]
            path.reverse()
            return True, path, len(path) - 1, states_expanded

        for neighbor in get_neighbors(grid, current):
            if neighbor not in visited:
                visited.add(neighbor)
                parent[neighbor] = current
                queue.append(neighbor)

    return False, [], 0, states_expanded
