"""
Script comparing Breadth-First Search (BFS) and A* Search (Manhattan) on Map 1.
Generates results/comparison.md.

[LLM-GENERATED CODE] - Generated by Gemini AI based on student specification.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from astar import astar_search, manhattan_distance
from bfs import bfs_search

MAP_ORIGINAL = """#################
#S....#.........#
#.###.#.#######.#
#...#.#.......#.#
###.#.#######.#.#
#...#.........#.#
#.###########.#.#
#.............#G#
#################"""


def parse_grid(grid_str):
    lines = [line.strip() for line in grid_str.strip().split('\n') if line.strip()]
    grid = []
    start = None
    goal = None
    for r, line in enumerate(lines):
        row = []
        for c, char in enumerate(line):
            row.append(char)
            if char == 'S':
                start = (r, c)
            elif char == 'G':
                goal = (r, c)
        grid.append(row)
    return grid, start, goal


def main():
    grid, start, goal = parse_grid(MAP_ORIGINAL)

    b_found, b_path, b_len, b_exp = bfs_search(grid, start, goal)
    a_found, a_path, a_len, a_exp = astar_search(grid, start, goal, manhattan_distance)

    md_content = f"""# Search Algorithm Comparison: BFS vs A*

This document presents the empirical comparison between **Breadth-First Search (BFS)** and **A* Search (Manhattan Heuristic)** on the original 17×9 warehouse map.

## Empirical Comparison Table

| Metric | Breadth-First Search (BFS) | A* Search (Manhattan) |
| :--- | :--- | :--- |
| **Solution Found** | {'Yes' if b_found else 'No'} | {'Yes' if a_found else 'No'} |
| **Path Length (Moves)** | {b_len} | {a_len} |
| **States Expanded** | {b_exp} | {a_exp} |

## Path Verification

- **BFS Path**: `{b_path}`
- **A* Path**: `{a_path}`
- **Paths Identical**: {b_path == a_path}

## Analysis of Results

1. **Optimality**: Both BFS and A* (with an admissible Manhattan heuristic) successfully find the optimal shortest path of length **40** moves.
2. **State Expansions**: On this specific warehouse map, both algorithms expand exactly **64 states**. This occurs because the warehouse map consists of a highly constrained single corridor with dead-end alcoves. Since the start is at `(1, 1)` and the goal is at `(7, 15)`, every reachable cell on the map (64 cells total) must be explored to reach the goal, regardless of heuristic guidance.
3. **Efficiency**: While A* utilizes goal directionality via $h(n)$, grid constraint topology dominates search space exploration in single-corridor mazes.
"""

    results_dir = os.path.join(os.path.dirname(__file__), '..', 'results')
    os.makedirs(results_dir, exist_ok=True)
    out_path = os.path.join(results_dir, 'comparison.md')

    with open(out_path, 'w') as f:
        f.write(md_content)

    print(f"[INFO] Successfully generated BFS vs A* comparison at: {out_path}")


if __name__ == "__main__":
    main()
