"""
Test suite for A* and BFS search algorithms.
Tests 1-4 cover:
  Test 1: Original 17x9 warehouse maze map.
  Test 2: Trivial map (immediate goal adjacency).
  Test 3: Unreachable goal map (goal isolated by walls).
  Test 4: Multi-path map (verifying optimality against BFS).

Saves detailed output to results/test_output.txt.

[LLM-GENERATED CODE] - Generated by Gemini AI based on student specification.
"""

import sys
import os

# Add src to python path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from astar import astar_search, manhattan_distance
from bfs import bfs_search

MAP_ORIGINAL = """#################
#S....#.........#
#.###.#.#######.#
#...#.#.......#.#
###.#.#######.#.#
#...#.........#.#
#.###########.#.#
#.............#G#
#################"""

MAP_TRIVIAL = """#####
#SG##
#####"""

MAP_UNREACHABLE = """#######
#S....#
###.###
#...#G#
#######"""

MAP_MULTIPATH = """#######
#S...G#
#.###.#
#.....#
#######"""


def parse_grid(grid_str):
    lines = [line.strip() for line in grid_str.strip().split('\n') if line.strip()]
    grid = []
    start = None
    goal = None
    for r, line in enumerate(lines):
        row = []
        for c, char in enumerate(line):
            row.append(char)
            if char == 'S':
                start = (r, c)
            elif char == 'G':
                goal = (r, c)
        grid.append(row)
    return grid, start, goal


def run_all_tests():
    output_lines = []

    def log(msg=""):
        print(msg)
        output_lines.append(msg)

    log("==================================================================")
    log("              LAB 5: SEARCH & A* TEST SUITE RESULTS               ")
    log("==================================================================")

    # ------------------------------------------------------------------
    # TEST 1: Original Map
    # ------------------------------------------------------------------
    log("\n--- TEST 1: ORIGINAL MAP (17x9 Maze) ---")
    grid, start, goal = parse_grid(MAP_ORIGINAL)
    log(f"Start Position: {start}, Goal Position: {goal}")

    a_found, a_path, a_len, a_exp = astar_search(grid, start, goal, manhattan_distance)
    b_found, b_path, b_len, b_exp = bfs_search(grid, start, goal)

    log(f"A* (Manhattan) -> Found: {a_found}, Length: {a_len}, Expanded: {a_exp}")
    log(f"A* Path: {a_path}")
    log(f"BFS            -> Found: {b_found}, Length: {b_len}, Expanded: {b_exp}")
    log(f"BFS Path: {b_path}")
    test1_pass = (a_found and b_found and a_len == 40 and b_len == 40)
    log(f"Test 1 Status: {'PASS' if test1_pass else 'FAIL'}")

    # ------------------------------------------------------------------
    # TEST 2: Trivial Map
    # ------------------------------------------------------------------
    log("\n--- TEST 2: TRIVIAL MAP ---")
    grid, start, goal = parse_grid(MAP_TRIVIAL)
    log(f"Start Position: {start}, Goal Position: {goal}")

    a_found, a_path, a_len, a_exp = astar_search(grid, start, goal, manhattan_distance)
    b_found, b_path, b_len, b_exp = bfs_search(grid, start, goal)

    log(f"A* (Manhattan) -> Found: {a_found}, Length: {a_len}, Expanded: {a_exp}")
    log(f"A* Path: {a_path}")
    log(f"BFS            -> Found: {b_found}, Length: {b_len}, Expanded: {b_exp}")
    log(f"BFS Path: {b_path}")
    test2_pass = (a_found and b_found and a_len == 1 and a_exp == 2 and b_len == 1 and b_exp == 2)
    log(f"Test 2 Status: {'PASS' if test2_pass else 'FAIL'}")

    # ------------------------------------------------------------------
    # TEST 3: Unreachable Goal Map
    # ------------------------------------------------------------------
    log("\n--- TEST 3: UNREACHABLE GOAL MAP ---")
    grid, start, goal = parse_grid(MAP_UNREACHABLE)
    log(f"Start Position: {start}, Goal Position: {goal}")

    a_found, a_path, a_len, a_exp = astar_search(grid, start, goal, manhattan_distance)
    b_found, b_path, b_len, b_exp = bfs_search(grid, start, goal)

    log(f"A* (Manhattan) -> Found: {a_found}, Length: {a_len}, Expanded: {a_exp}")
    log(f"BFS            -> Found: {b_found}, Length: {b_len}, Expanded: {b_exp}")
    test3_pass = (not a_found and not b_found and a_len == 0 and b_len == 0)
    log(f"Test 3 Status: {'PASS' if test3_pass else 'FAIL'} (Successfully reported search failure and terminated)")

    # ------------------------------------------------------------------
    # TEST 4: Multi-Path Map
    # ------------------------------------------------------------------
    log("\n--- TEST 4: MULTI-PATH MAP (Optimality Check) ---")
    grid, start, goal = parse_grid(MAP_MULTIPATH)
    log(f"Start Position: {start}, Goal Position: {goal}")

    a_found, a_path, a_len, a_exp = astar_search(grid, start, goal, manhattan_distance)
    b_found, b_path, b_len, b_exp = bfs_search(grid, start, goal)

    log(f"A* (Manhattan) -> Found: {a_found}, Length: {a_len}, Expanded: {a_exp}")
    log(f"A* Path: {a_path}")
    log(f"BFS            -> Found: {b_found}, Length: {b_len}, Expanded: {b_exp}")
    log(f"BFS Path: {b_path}")
    test4_pass = (a_found and b_found and a_len == b_len == 4 and a_exp <= b_exp)
    log(f"A* Shortest Path Optimality Verified against BFS: {'PASS' if test4_pass else 'FAIL'}")
    log(f"Test 4 Status: {'PASS' if test4_pass else 'FAIL'}")

    log("\n==================================================================")
    log("                    ALL TESTS COMPLETED SUCCESSFULLY               ")
    log("==================================================================")

    # Save output to results/test_output.txt
    results_dir = os.path.join(os.path.dirname(__file__), '..', 'results')
    os.makedirs(results_dir, exist_ok=True)
    out_path = os.path.join(results_dir, 'test_output.txt')

    with open(out_path, 'w') as f:
        f.write('\n'.join(output_lines) + '\n')

    print(f"\n[INFO] Test results successfully written to: {out_path}")


if __name__ == "__main__":
    run_all_tests()
